### ISSUE TITLE
warnings with flutter 3.0.4

### ISSUE THREAD

**Issue by blindguydiy** [Mrbluesky-ai/flutter-alarmplayer#1]
the following warnings when working with flutter 3.0.4. \alarmplayer-1.0.3\android\src\main\java\com\Mrblueskyai\alarmplayer\AlarmplayerPlugin.java:86: warning: [deprecation] setAudioStreamType(int) in MediaPlayer has been deprecated
          mMediaPlayer.setAudioStreamType(AudioManager.STREAM_ALARM);
         Get following when using with flutter 3.0.4 \alarmplayer-1.0.3\android\src\main\java\com\Mrblueskyai\alarmplayer\AlarmplayerPlugin.java:86: warning: [deprecation] setAudioStreamType(int) in MediaPlayer has been deprecated
          mMediaPlayer.setAudioStreamType(AudioManager.STREAM_ALARM);

**Comment by Mrbluesky-ai** [comment]
hi @blindguydiy , thanks for using my plugin! i made a new version (version 1.0.4) of this plugin where this warning is fixed. if you encounter any other problem feel free to open a new issue. i will close this issue.
